<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| WARNING: You MUST set this value!
|
| If it is not set, then CodeIgniter will try to guess the protocol and
| path to your installation, but due to security concerns the hostname will
| be set to $_SERVER['SERVER_ADDR'] if available, or localhost otherwise.
| The auto-detection mechanism exists only for convenience during
| development and MUST NOT be used in production!
|
| If you need to allow multiple domains, remember that this file is still
| a PHP script and you can easily do that on your own.
|
*/
$config['base_url'] = 'http://localhost/fuzzymam/';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'REQUEST_URI' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'REQUEST_URI'    Uses $_SERVER['REQUEST_URI']
| 'QUERY_STRING'   Uses $_SERVER['QUERY_STRING']
| 'PATH_INFO'      Uses $_SERVER['PATH_INFO']
|
| WARNING: If you set this to 'PATH_INFO', URIs will always be URL-decoded!
*/
$config['uri_protocol']	= 'REQUEST_URI';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| https://codeigniter.com/userguide3/general/urls.html
|
| Note: This option is ignored for CLI requests.
*/
$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
| See http://php.net/htmlspecialchars for a list of supported charsets.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = FALSE;

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| https://codeigniter.com/userguide3/general/core_classes.html
| https://codeigniter.com/userguide3/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

/*
|--------------------------------------------------------------------------
| Composer auto-loading
|--------------------------------------------------------------------------
|
| Enabling this setting will tell CodeIgniter to look for a Composer
| package auto-loader script in application/vendor/autoload.php.
|
|	$config['composer_autoload'] = TRUE;
|
| Or if you have your vendor/ directory located somewhere else, you
| can opt to set a specific path as well:
|
|	$config['composer_autoload'] = '/path/to/vendor/autoload.php';
|
| For more information about Composer, please visit http://getcomposer.org/
|
| Note: This will NOT disable or override the CodeIgniter-specific
|	autoloading (application/config/autoload.php)
*/
$config['composer_autoload'] = FALSE;

/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify which characters are permitted within your URLs.
| When someone tries to submit a URL with disallowed characters they will
| get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| The configured value is actually a regular expression character group
| and it will be executed as: ! preg_match('/^[<permitted_uri_chars>]+$/i
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';

/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['enable_query_strings'] = FALSE;
$config['controller_trigger'] = 'c';
$config['function_trigger'] = 'm';
$config['directory_trigger'] = 'd';

/*
|--------------------------------------------------------------------------
| Allow $_GET array
|--------------------------------------------------------------------------
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['allow_get_array'] = TRUE;

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| You can also pass an array with threshold levels to show individual error types
|
| 	array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 0;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ directory. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Log File Extension
|--------------------------------------------------------------------------
|
| The default filename extension for log files. The default 'php' allows for
| protecting the log files via basic scripting, when they are to be stored
| under a publicly accessible directory.
|
| Note: Leaving it blank will default to 'php'.
|
*/
$config['log_file_extension'] = '';

/*
|--------------------------------------------------------------------------
| Log File Permissions
|--------------------------------------------------------------------------
|
| The file system permissions to be applied on newly created log files.
|
| IMPORTANT: This MUST be an integer (no quotes) and you MUST use octal
|            integer notation (i.e. 0700, 0644, etc.)
*/
$config['log_file_permissions'] = 0644;

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Error Views Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/views/errors/ directory.  Use a full server path with trailing slash.
|
*/
$config['error_views_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/cache/ directory.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Cache Include Query String
|--------------------------------------------------------------------------
|
| Whether to take the URL query string into consideration when generating
| output cache files. Valid options are:
|
|	FALSE      = Disabled
|	TRUE       = Enabled, take all query parameters into account.
|	             Please be aware that this may result in numerous cache
|	             files generated for the same page over and over again.
|	array('q') = Enabled, but only take into account the specified list
|	             of query parameters.
|
*/
$config['cache_query_string'] = FALSE;

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class, you must set an encryption key.
| See the user guide for more info.
|
| https://codeigniter.com/userguide3/libraries/encryption.html
|
*/
$config['encryption_key'] = '9140888d44f5edda5c77ada9ed598845f69ea57508211d62ec0d2ad68202deed';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_driver'
|
|	The storage driver to use: files, database, redis, memcached
|
| 'sess_cookie_name'
|
|	The session cookie name, must contain only [0-9a-z_-] characters
|
| 'sess_samesite'
|
|	Session cookie SameSite attribute: Lax (default), Strict or None
|
| 'sess_expiration'
|
|	The number of SECONDS you want the session to last.
|	Setting to 0 (zero) means expire when the browser is closed.
|
| 'sess_save_path'
|
|	The location to save sessions to, driver dependent.
|
|	For the 'files' driver, it's a path to a writable directory.
|	WARNING: Only absolute paths are supported!
|
|	For the 'database' driver, it's a table name.
|	Please read up the manual for the format with other session drivers.
|
|	IMPORTANT: You are REQUIRED to set a valid save path!
|
| 'sess_match_ip'
|
|	Whether to match the user's IP address when reading the session data.
|
|	WARNING: If you're using the database driver, don't forget to update
|	         your session table's PRIMARY KEY when changing this setting.
|
| 'sess_time_to_update'
|
|	How many seconds between CI regenerating the session ID.
|
| 'sess_regenerate_destroy'
|
|	Whether to destroy session data associated with the old session ID
|	when auto-regenerating the session ID. When set to FALSE, the data
|	will be later deleted by the garbage collector.
|
| Other session cookie settings are shared with the rest of the application,
| except for 'cookie_prefix' and 'cookie_httponly', which are ignored here.
|
*/
$config['sess_driver'] = 'files';
$config['sess_cookie_name'] = 'ci_session';
$config['sess_samesite'] = 'Lax';
$config['sess_expiration'] = 7200;
$config['sess_save_path'] = NULL;
$config['sess_match_ip'] = FALSE;
$config['sess_time_to_update'] = 300;
$config['sess_regenerate_destroy'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix'   = Set a cookie name prefix if you need to avoid collisions
| 'cookie_domain'   = Set to .your-domain.com for site-wide cookies
| 'cookie_path'     = Typically will be a forward slash
| 'cookie_secure'   = Cookie will only be set if a secure HTTPS connection exists.
| 'cookie_httponly' = Cookie will only be accessible via HTTP(S) (no javascript)
| 'cookie_samesite' = Cookie's samesite attribute (Lax, Strict or None)
|
| Note: These settings (with the exception of 'cookie_prefix' and
|       'cookie_httponly') will also affect sessions.
|
*/
$config['cookie_prefix']	= '';
$config['cookie_domain']	= '';
$config['cookie_path']		= '/';
$config['cookie_secure']	= FALSE;
$config['cookie_httponly'] 	= FALSE;
$config['cookie_samesite'] 	= 'Lax';

/*
|--------------------------------------------------------------------------
| Standardize newlines
|--------------------------------------------------------------------------
|
| Determines whether to standardize newline characters in input data,
| meaning to replace \r\n, \r, \n occurrences with the PHP_EOL value.
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['standardize_newlines'] = FALSE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
| WARNING: This feature is DEPRECATED and currently available only
|          for backwards compatibility purposes!
|
*/
$config['global_xss_filtering'] = FALSE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_regenerate' = Regenerate token on every submission
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection'] = FALSE;
$config['csrf_token_name'] = 'csrf_test_name';
$config['csrf_cookie_name'] = 'csrf_cookie_name';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = TRUE;
$config['csrf_exclude_uris'] = array();

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| Only used if zlib.output_compression is turned off in your php.ini.
| Please do not use it together with httpd-level output compression.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or any PHP supported timezone. This preference tells
| the system whether to use your server's local time as the master 'now'
| reference, or convert it to the configured one timezone. See the 'date
| helper' page of the user guide for information regarding date handling.
|
*/
$config['time_reference'] = 'local';

/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
| Note: You need to have eval() enabled for this to work.
|
*/
$config['rewrite_short_tags'] = FALSE;

/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy
| IP addresses from which CodeIgniter should trust headers such as
| HTTP_X_FORWARDED_FOR and HTTP_CLIENT_IP in order to properly identify
| the visitor's IP address.
|
| You can use both an array or a comma-separated list of proxy addresses,
| as well as specifying whole subnets. Here are a few examples:
|
| Comma-separated:	'10.0.1.200,192.168.5.0/24'
| Array:		array('10.0.1.200', '192.168.5.0/24')
*/
$config['proxy_ips'] = '';

$config['geojson_kotakediri'][] = '{
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [112.002835, -7.771528],
                [112.001289, -7.771071],
                [111.999357, -7.771702],
                [111.998588, -7.771568],
                [111.997375, -7.771506],
                [111.997379, -7.771489],
                [111.997265, -7.77158],
                [111.996427, -7.774313],
                [111.995816, -7.774509],
                [111.995554, -7.774592],
                [111.992599, -7.775538],
                [111.99173, -7.777362],
                [111.99131, -7.778941],
                [111.990633, -7.781457],
                [111.986302, -7.781224],
                [111.98603, -7.781215],
                [111.985496, -7.781195],
                [111.984825, -7.781072],
                [111.984344, -7.781031],
                [111.983886, -7.78095],
                [111.98349, -7.78093],
                [111.98349, -7.78093],
                [111.983429, -7.781677],
                [111.98339, -7.78232],
                [111.98336, -7.782812],
                [111.983329, -7.783295],
                [111.98323, -7.784022],
                [111.983198, -7.784219],
                [111.983085, -7.784914],
                [111.982971, -7.785447],
                [111.982902, -7.785766],
                [111.982696, -7.786679],
                [111.982505, -7.787364],
                [111.982338, -7.787891],
                [111.982261, -7.788133],
                [111.981994, -7.788596],
                [111.981636, -7.788964],
                [111.981094, -7.789235],
                [111.980514, -7.789465],
                [111.979988, -7.7898],
                [111.97953, -7.790182],
                [111.979509, -7.790213],
                [111.979164, -7.790724],
                [111.978828, -7.791504],
                [111.978649, -7.792099],
                [111.977821, -7.792674],
                [111.97657, -7.793539],
                [111.973343, -7.792207],
                [111.97126, -7.791138],
                [111.969261, -7.791213],
                [111.96711, -7.79203],
                [111.964554, -7.793673],
                [111.962608, -7.794777],
                [111.960602, -7.795537],
                [111.956299, -7.796742],
                [111.955391, -7.800852],
                [111.95538, -7.800946],
                [111.955124, -7.803194],
                [111.955025, -7.805851],
                [111.955014, -7.80745],
                [111.954803, -7.807727],
                [111.954597, -7.808284],
                [111.954582, -7.808886],
                [111.95446, -7.809715],
                [111.954445, -7.810506],
                [111.954444, -7.810508],
                [111.954406, -7.811577],
                [111.954406, -7.812404],
                [111.954506, -7.813183],
                [111.95462, -7.813726],
                [111.954742, -7.814406],
                [111.955024, -7.815214],
                [111.955269, -7.815813],
                [111.955291, -7.815871],
                [111.955345, -7.816014],
                [111.95536, -7.816069],
                [111.955398, -7.816175],
                [111.955421, -7.816239],
                [111.955459, -7.816344],
                [111.955482, -7.816379],
                [111.955497, -7.81644],
                [111.95552, -7.816483],
                [111.955604, -7.81663],
                [111.955622, -7.816674],
                [111.955642, -7.816725],
                [111.955833, -7.817047],
                [111.955909, -7.81718],
                [111.955993, -7.817279],
                [111.956062, -7.817377],
                [111.956344, -7.817723],
                [111.956371, -7.817749],
                [111.956421, -7.817909],
                [111.957813, -7.819101],
                [111.95784, -7.819293],
                [111.957695, -7.819479],
                [111.957397, -7.819887],
                [111.957336, -7.819976],
                [111.957191, -7.820652],
                [111.957245, -7.820719],
                [111.957382, -7.820733],
                [111.957641, -7.820771],
                [111.957695, -7.820917],
                [111.957779, -7.821299],
                [111.957962, -7.822052],
                [111.958023, -7.822493],
                [111.95803, -7.822522],
                [111.958091, -7.82286],
                [111.958586, -7.822997],
                [111.95916, -7.823157],
                [111.959625, -7.823221],
                [111.960113, -7.823218],
                [111.960823, -7.823194],
                [111.961128, -7.82328],
                [111.961738, -7.8235],
                [111.961959, -7.823495],
                [111.96219, -7.823453],
                [111.962448, -7.823406],
                [111.962814, -7.823348],
                [111.963005, -7.823376],
                [111.963821, -7.823921],
                [111.964157, -7.824032],
                [111.964249, -7.824048],
                [111.964538, -7.824097],
                [111.96508, -7.824135],
                [111.965446, -7.824078],
                [111.965744, -7.824141],
                [111.966346, -7.824132],
                [111.966766, -7.824092],
                [111.967407, -7.824091],
                [111.968475, -7.824057],
                [111.96848, -7.824057],
                [111.969284, -7.824084],
                [111.969925, -7.824117],
                [111.970504, -7.82418],
                [111.971557, -7.824225],
                [111.972625, -7.824318],
                [111.973347, -7.824334],
                [111.973564, -7.824339],
                [111.973884, -7.824346],
                [111.974991, -7.824439],
                [111.975242, -7.824481],
                [111.976326, -7.824659],
                [111.977096, -7.824848],
                [111.977974, -7.825211],
                [111.978836, -7.825665],
                [111.979362, -7.825945],
                [111.97982, -7.82619],
                [111.980064, -7.82632],
                [111.980613, -7.82662],
                [111.980957, -7.826815],
                [111.981392, -7.827055],
                [111.981773, -7.82723],
                [111.982071, -7.82735],
                [111.982414, -7.827434],
                [111.982658, -7.827454],
                [111.982832, -7.827466],
                [111.985001, -7.82725],
                [111.986969, -7.8296],
                [111.985588, -7.832022],
                [111.984784, -7.833782],
                [111.984787, -7.833835],
                [111.984741, -7.834422],
                [111.984668, -7.835125],
                [111.984657, -7.835234],
                [111.98455, -7.835902],
                [111.984459, -7.836506],
                [111.984344, -7.837031],
                [111.984246, -7.837637],
                [111.984245, -7.837641],
                [111.984222, -7.837785],
                [111.98426, -7.837916],
                [111.984382, -7.83806],
                [111.984474, -7.838124],
                [111.984611, -7.83822],
                [111.984893, -7.838359],
                [111.985641, -7.838641],
                [111.98584, -7.838725],
                [111.98584, -7.838726],
                [111.986015, -7.838801],
                [111.986256, -7.83892],
                [111.98629, -7.838936],
                [111.986549, -7.839102],
                [111.986617, -7.839183],
                [111.986732, -7.839321],
                [111.986839, -7.839431],
                [111.986885, -7.839463],
                [111.987014, -7.839526],
                [111.987099, -7.839511],
                [111.987159, -7.839501],
                [111.987381, -7.839397],
                [111.987935, -7.839111],
                [111.98896, -7.839311],
                [111.992607, -7.839747],
                [111.99275, -7.839784],
                [111.995201, -7.840418],
                [111.998634, -7.840951],
                [112.003609, -7.842511],
                [112.004188, -7.845274],
                [112.004264, -7.845635],
                [112.004379, -7.846184],
                [112.004205, -7.846466],
                [112.002708, -7.848889],
                [112.000771, -7.85165],
                [111.999875, -7.85268],
                [112.00096, -7.853113],
                [112.001399, -7.853286],
                [112.00243, -7.853735],
                [112.003493, -7.854173],
                [112.003725, -7.854268],
                [112.003915, -7.854346],
                [112.004262, -7.854458],
                [112.004295, -7.854466],
                [112.004543, -7.85454],
                [112.005622, -7.854861],
                [112.006813, -7.855245],
                [112.007629, -7.855467],
                [112.00763, -7.855467],
                [112.007675, -7.85548],
                [112.007682, -7.855484],
                [112.007701, -7.855489],
                [112.007703, -7.855488],
                [112.008896, -7.855831],
                [112.009439, -7.855984],
                [112.009666, -7.856048],
                [112.01014, -7.856086],
                [112.010337, -7.856102],
                [112.010339, -7.856102],
                [112.01059, -7.856032],
                [112.010635, -7.85602],
                [112.011298, -7.855743],
                [112.011223, -7.855927],
                [112.010765, -7.858348],
                [112.010704, -7.859794],
                [112.010963, -7.861764],
                [112.01413, -7.861382],
                [112.01671, -7.861467],
                [112.017242, -7.861485],
                [112.018974, -7.862638],
                [112.019745, -7.864985],
                [112.019989, -7.866986],
                [112.020859, -7.867563],
                [112.022112, -7.8684],
                [112.02224, -7.868484],
                [112.025467, -7.869045],
                [112.029129, -7.869408],
                [112.033127, -7.87003],
                [112.035957, -7.870588],
                [112.03786, -7.870995],
                [112.038979, -7.871233],
                [112.042412, -7.871709],
                [112.043176, -7.871246],
                [112.04329, -7.871176],
                [112.044792, -7.870265],
                [112.047577, -7.867766],
                [112.049841, -7.868271],
                [112.049875, -7.868279],
                [112.050591, -7.868439],
                [112.051552, -7.868902],
                [112.055565, -7.871324],
                [112.055737, -7.871458],
                [112.055695, -7.871087],
                [112.055663, -7.870747],
                [112.05541, -7.870588],
                [112.05538, -7.870357],
                [112.055737, -7.86951],
                [112.055736, -7.869319],
                [112.05642, -7.867717],
                [112.056465, -7.867611],
                [112.056693, -7.866948],
                [112.056737, -7.866376],
                [112.056737, -7.866125],
                [112.056598, -7.865576],
                [112.05661, -7.865577],
                [112.05724, -7.865598],
                [112.057629, -7.865597],
                [112.05795, -7.865436],
                [112.058026, -7.865129],
                [112.059303, -7.865301],
                [112.059355, -7.865315],
                [112.059722, -7.865414],
                [112.060127, -7.865523],
                [112.060191, -7.865545],
                [112.060617, -7.865692],
                [112.06118, -7.865887],
                [112.062248, -7.866401],
                [112.063133, -7.866777],
                [112.063297, -7.866839],
                [112.063302, -7.866839],
                [112.063453, -7.866897],
                [112.064514, -7.867303],
                [112.064845, -7.867506],
                [112.065246, -7.867753],
                [112.066002, -7.868296],
                [112.066663, -7.868778],
                [112.066952, -7.869941],
                [112.067352, -7.871553],
                [112.06849, -7.872876],
                [112.068524, -7.873555],
                [112.069014, -7.874912],
                [112.069281, -7.874991],
                [112.069285, -7.874973],
                [112.069366, -7.874664],
                [112.069708, -7.873954],
                [112.070141, -7.872971],
                [112.070003, -7.872879],
                [112.070183, -7.872586],
                [112.070198, -7.872595],
                [112.0702, -7.872595],
                [112.070968, -7.872851],
                [112.071454, -7.872838],
                [112.071509, -7.872692],
                [112.071831, -7.872829],
                [112.072392, -7.872757],
                [112.072413, -7.872693],
                [112.072439, -7.87261],
                [112.073244, -7.870082],
                [112.073262, -7.870026],
                [112.072994, -7.869876],
                [112.073284, -7.869235],
                [112.073488, -7.868758],
                [112.073556, -7.868591],
                [112.073742, -7.868064],
                [112.073005, -7.867571],
                [112.072381, -7.867278],
                [112.07251, -7.866941],
                [112.072559, -7.866788],
                [112.072166, -7.866511],
                [112.071586, -7.866257],
                [112.071052, -7.865363],
                [112.070891, -7.865076],
                [112.070794, -7.864975],
                [112.07057, -7.864742],
                [112.069695, -7.863699],
                [112.069233, -7.863151],
                [112.068489, -7.862464],
                [112.068274, -7.862285],
                [112.067345, -7.861513],
                [112.067067, -7.861282],
                [112.065918, -7.860404],
                [112.065915, -7.859631],
                [112.066018, -7.858537],
                [112.066372, -7.857634],
                [112.066627, -7.856015],
                [112.066629, -7.856007],
                [112.066587, -7.855761],
                [112.06656, -7.8556],
                [112.06649, -7.8554],
                [112.06637, -7.85492],
                [112.06639, -7.85473],
                [112.06652, -7.85442],
                [112.06658, -7.85417],
                [112.06653, -7.85405],
                [112.06641, -7.85392],
                [112.06586, -7.85334],
                [112.06575, -7.85307],
                [112.065587, -7.85277],
                [112.06557, -7.85274],
                [112.06522, -7.85217],
                [112.065186, -7.851978],
                [112.067741, -7.852074],
                [112.068279, -7.852448],
                [112.068322, -7.852477],
                [112.068674, -7.851782],
                [112.068818, -7.851425],
                [112.069083, -7.850847],
                [112.068408, -7.850526],
                [112.068105, -7.850665],
                [112.06763, -7.850396],
                [112.067142, -7.850119],
                [112.0667, -7.849868],
                [112.065833, -7.849221],
                [112.065544, -7.848967],
                [112.065403, -7.848778],
                [112.065047, -7.848496],
                [112.064805, -7.848168],
                [112.06518, -7.84826],
                [112.0661, -7.84852],
                [112.06683, -7.84867],
                [112.067758, -7.849045],
                [112.067841, -7.848828],
                [112.067954, -7.848613],
                [112.06798, -7.848564],
                [112.068111, -7.84833],
                [112.068184, -7.848186],
                [112.06855, -7.847344],
                [112.068202, -7.847046],
                [112.068205, -7.847036],
                [112.068672, -7.845597],
                [112.069534, -7.845167],
                [112.070297, -7.845291],
                [112.07164, -7.84582],
                [112.072204, -7.846088],
                [112.072209, -7.84625],
                [112.072124, -7.846479],
                [112.072116, -7.846665],
                [112.07227, -7.84686],
                [112.072814, -7.847011],
                [112.073844, -7.847534],
                [112.074542, -7.84793],
                [112.074865, -7.848082],
                [112.075865, -7.848499],
                [112.076537, -7.84876],
                [112.077013, -7.84898],
                [112.077031, -7.848988],
                [112.07749, -7.849148],
                [112.077586, -7.849167],
                [112.077967, -7.848329],
                [112.078067, -7.848039],
                [112.078294, -7.847524],
                [112.078433, -7.847246],
                [112.078495, -7.847121],
                [112.078695, -7.84657],
                [112.078719, -7.846578],
                [112.080036, -7.847011],
                [112.080238, -7.846278],
                [112.080246, -7.846252],
                [112.08036, -7.845933],
                [112.080395, -7.8458],
                [112.080433, -7.845811],
                [112.080845, -7.844093],
                [112.080984, -7.844123],
                [112.081047, -7.843879],
                [112.081389, -7.842675],
                [112.080848, -7.842579],
                [112.080662, -7.84258],
                [112.080425, -7.842656],
                [112.079259, -7.842194],
                [112.079099, -7.842062],
                [112.079187, -7.841735],
                [112.078379, -7.841489],
                [112.078388, -7.841454],
                [112.078441, -7.841082],
                [112.078325, -7.840888],
                [112.078307, -7.840782],
                [112.0783, -7.840467],
                [112.078156, -7.840257],
                [112.078022, -7.840136],
                [112.077756, -7.840169],
                [112.077534, -7.840093],
                [112.077335, -7.840093],
                [112.077091, -7.840094],
                [112.076846, -7.839851],
                [112.076912, -7.839641],
                [112.076457, -7.839454],
                [112.076401, -7.839056],
                [112.076455, -7.838736],
                [112.075945, -7.838593],
                [112.075867, -7.838538],
                [112.07525, -7.838284],
                [112.075649, -7.837102],
                [112.075677, -7.836978],
                [112.075221, -7.836785],
                [112.075165, -7.836763],
                [112.07503, -7.836703],
                [112.074617, -7.836543],
                [112.07454, -7.836505],
                [112.074373, -7.836904],
                [112.074172, -7.837357],
                [112.073955, -7.837254],
                [112.073945, -7.837277],
                [112.073494, -7.838344],
                [112.073399, -7.838584],
                [112.073101, -7.839312],
                [112.072687, -7.840234],
                [112.072523, -7.84054],
                [112.072789, -7.840681],
                [112.072461, -7.841475],
                [112.072461, -7.841475],
                [112.070826, -7.8405],
                [112.070999, -7.83749],
                [112.069458, -7.836824],
                [112.068192, -7.836497],
                [112.067708, -7.836371],
                [112.067438, -7.836301],
                [112.067434, -7.8363],
                [112.066978, -7.836182],
                [112.062347, -7.835642],
                [112.060677, -7.836919],
                [112.057907, -7.836218],
                [112.056404, -7.834267],
                [112.056008, -7.833975],
                [112.055979, -7.833954],
                [112.055967, -7.83399],
                [112.055877, -7.83418],
                [112.055836, -7.834262],
                [112.055806, -7.834318],
                [112.055804, -7.834323],
                [112.05565, -7.834219],
                [112.055327, -7.834062],
                [112.055007, -7.833866],
                [112.054799, -7.833787],
                [112.054457, -7.833651],
                [112.054195, -7.833509],
                [112.05422, -7.833452],
                [112.054447, -7.832934],
                [112.055206, -7.833008],
                [112.055306, -7.832812],
                [112.055089, -7.83272],
                [112.055163, -7.832465],
                [112.054772, -7.832272],
                [112.052548, -7.831334],
                [112.052996, -7.83021],
                [112.052369, -7.829944],
                [112.05226, -7.829898],
                [112.052158, -7.829866],
                [112.051362, -7.829619],
                [112.051123, -7.830191],
                [112.05109, -7.830251],
                [112.051105, -7.830325],
                [112.051145, -7.830525],
                [112.05126, -7.830794],
                [112.051288, -7.830855],
                [112.051211, -7.831226],
                [112.051182, -7.831367],
                [112.051136, -7.83159],
                [112.051121, -7.831659],
                [112.051116, -7.831682],
                [112.050849, -7.831563],
                [112.05079, -7.831536],
                [112.050704, -7.831498],
                [112.050415, -7.831369],
                [112.050361, -7.831345],
                [112.05017, -7.831258],
                [112.050046, -7.831202],
                [112.049958, -7.831358],
                [112.049834, -7.831572],
                [112.04977, -7.831687],
                [112.049698, -7.831814],
                [112.049694, -7.83182],
                [112.049686, -7.831831],
                [112.049643, -7.83181],
                [112.049637, -7.8318],
                [112.049582, -7.831754],
                [112.049532, -7.831706],
                [112.049484, -7.831598],
                [112.049409, -7.831321],
                [112.049361, -7.831017],
                [112.04936, -7.830773],
                [112.049411, -7.830576],
                [112.049165, -7.830221],
                [112.049127, -7.830134],
                [112.04902, -7.830046],
                [112.048995, -7.830041],
                [112.048977, -7.830031],
                [112.048958, -7.830023],
                [112.048887, -7.830002],
                [112.048725, -7.829966],
                [112.04848, -7.829856],
                [112.048173, -7.829718],
                [112.047329, -7.829394],
                [112.046674, -7.829121],
                [112.046174, -7.828942],
                [112.045743, -7.828797],
                [112.045613, -7.828683],
                [112.045225, -7.828343],
                [112.044919, -7.828161],
                [112.044338, -7.82787],
                [112.04343, -7.827524],
                [112.042732, -7.827258],
                [112.042954, -7.826736],
                [112.043318, -7.825878],
                [112.043318, -7.825832],
                [112.043318, -7.825609],
                [112.043053, -7.825133],
                [112.043423, -7.823957],
                [112.043492, -7.823738],
                [112.043381, -7.823463],
                [112.043358, -7.82344],
                [112.043348, -7.823429],
                [112.043288, -7.823261],
                [112.043183, -7.823142],
                [112.043053, -7.823065],
                [112.04285, -7.822977],
                [112.042564, -7.822879],
                [112.042247, -7.822714],
                [112.041869, -7.822515],
                [112.041672, -7.822449],
                [112.041458, -7.822366],
                [112.041261, -7.822367],
                [112.041074, -7.822341],
                [112.040964, -7.822269],
                [112.040834, -7.82215],
                [112.040704, -7.82201],
                [112.040535, -7.821951],
                [112.040353, -7.821869],
                [112.040129, -7.821688],
                [112.03977, -7.821476],
                [112.039415, -7.821213],
                [112.039254, -7.821115],
                [112.039103, -7.821011],
                [112.038978, -7.820846],
                [112.038879, -7.820747],
                [112.038732, -7.820714],
                [112.038271, -7.820279],
                [112.038028, -7.820165],
                [112.037629, -7.820166],
                [112.037132, -7.82021],
                [112.036337, -7.820045],
                [112.036317, -7.820041],
                [112.036083, -7.819959],
                [112.035638, -7.819823],
                [112.035042, -7.819573],
                [112.034509, -7.819337],
                [112.034221, -7.819223],
                [112.033968, -7.819123],
                [112.033692, -7.818987],
                [112.033294, -7.818812],
                [112.033533, -7.818305],
                [112.033712, -7.817963],
                [112.033709, -7.817955],
                [112.033752, -7.817885],
                [112.034057, -7.817173],
                [112.034195, -7.816922],
                [112.034446, -7.81638],
                [112.034515, -7.816196],
                [112.034568, -7.816059],
                [112.034813, -7.815568],
                [112.034817, -7.815559],
                [112.035028, -7.81503],
                [112.035555, -7.813533],
                [112.035609, -7.813371],
                [112.035671, -7.813188],
                [112.035707, -7.813082],
                [112.035785, -7.812929],
                [112.035835, -7.81283],
                [112.034877, -7.812428],
                [112.033385, -7.811829],
                [112.031993, -7.811269],
                [112.031829, -7.811694],
                [112.031753, -7.811877],
                [112.03139, -7.812813],
                [112.031359, -7.812894],
                [112.031196, -7.813335],
                [112.031127, -7.813504],
                [112.031111, -7.813558],
                [112.031083, -7.81365],
                [112.031055, -7.813742],
                [112.030915, -7.814134],
                [112.030327, -7.813746],
                [112.029427, -7.811574],
                [112.029388, -7.808287],
                [112.028595, -7.806197],
                [112.026093, -7.804458],
                [112.025862, -7.804128],
                [112.024841, -7.802661],
                [112.024485, -7.799588],
                [112.023826, -7.799393],
                [112.023492, -7.799294],
                [112.02282, -7.798976],
                [112.022405, -7.798779],
                [112.021889, -7.798534],
                [112.021039, -7.798126],
                [112.020615, -7.797991],
                [112.020012, -7.797897],
                [112.01997, -7.79788],
                [112.019314, -7.797625],
                [112.018625, -7.797221],
                [112.017911, -7.796801],
                [112.017697, -7.796688],
                [112.016144, -7.795836],
                [112.015968, -7.79574],
                [112.01597, -7.795658],
                [112.015975, -7.795595],
                [112.016012, -7.795196],
                [112.01603, -7.794998],
                [112.01605, -7.792748],
                [112.016047, -7.792701],
                [112.01601, -7.792138],
                [112.015964, -7.791595],
                [112.013628, -7.790628],
                [112.013543, -7.790628],
                [112.013549, -7.790595],
                [112.010922, -7.789782],
                [112.010771, -7.789989],
                [112.010615, -7.790201],
                [112.010581, -7.7902],
                [112.010441, -7.790192],
                [112.010421, -7.790191],
                [112.009724, -7.79012],
                [112.009299, -7.790084],
                [112.009214, -7.790075],
                [112.009109, -7.789189],
                [112.008728, -7.788031],
                [112.008835, -7.785831],
                [112.006195, -7.782843],
                [112.006156, -7.782322],
                [112.005959, -7.779669],
                [112.006317, -7.776985],
                [112.005363, -7.772608],
                [112.003456, -7.771712],
                [112.002835, -7.771528]
            ]
        ]
    },
    "properties": {
        "KABKOT": "KEDIRI",
        "PROVNO": "35",
        "KABKOTNO": "71",
        "PROVINSI": "JAWA TIMUR",
        "mhid": "1332:265",
        "shape": "Polygon",
        "name": "Unnamed Layer",
        "category": "default"
    },
    "id": "85399932-2dd3-43aa-ab8b-81a7c2554691"
}';

/*$config['geojson_kotakediri'][] = '{
    "type": "Feature",
    "properties": {
        "shape": "Polygon",
        "name": "HUTAN",
        "display_name": "Hutan"
    },
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [111.954506, -7.813183],
                [111.965875, -7.813725],
                [111.967292, -7.813512],
                [111.968193, -7.811472],
                [111.969695, -7.811132],
                [111.971756, -7.810919],
                [111.97343, -7.809984],
                [111.972743, -7.808836],
                [111.970897, -7.809303],
                [111.968923, -7.809133],
                [111.96815, -7.809176],
                [111.968239, -7.808368],
                [111.969226, -7.807858],
                [111.970256, -7.806199],
                [111.972961, -7.806752],
                [111.97494, -7.80654],
                [111.975369, -7.804371],
                [111.974897, -7.802373],
                [111.974382, -7.801012],
                [111.972665, -7.798121],
                [111.97348, -7.796378],
                [111.974081, -7.79472],
                [111.973343, -7.792207],
                [111.97126, -7.791138],
                [111.969261, -7.791213],
                [111.96711, -7.79203],
                [111.964554, -7.793673],
                [111.962608, -7.794777],
                [111.960602, -7.795537],
                [111.956299, -7.796742],
                [111.955391, -7.800852],
                [111.955124, -7.803194],
                [111.955025, -7.805851],
                [111.955014, -7.80745],
                [111.954803, -7.807727],
                [111.954597, -7.808284],
                [111.954582, -7.808886],
                [111.95446, -7.809715],
                [111.954444, -7.810508],
                [111.954417, -7.811286],
                [111.954406, -7.812404],
                [111.954506, -7.813183]
            ]
        ]
    },
    "id": "9922da48-97cf-4107-b04a-c18d13e89b9d"
}';*/